Grid styling
Maclenn77/Project-Embeding-Videos pull request #5
Opened 2020-02-20 15:16 UTC by Maclenn77

We created a clone of YouTube page, using HTML and CSS Grid Layout. We added video, images, buttons, and we used semantic tags, reusable CSS to style the position of elements. For icons, we use and external source from Google Apis. 

We validated the code through W3C validator for CSS and HTML.

2020-02-21 00:24 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @Maclenn77 and @markonikovic 

### Good job, your project looks professional and the youtube clone looks promising :v:  

### I have some changes still for you to make

## Page layout

I see you've used the http://archive.ph/Bss88 page and it's okay but this page has a ruler, the original page should be layered out taking 100% of the screen width like [this page](https://www.youtube.com/watch?v=V74l_zS1x8E) so let's fix it 

- Yours

![image](https://user-images.githubusercontent.com/52209067/74991616-0052f980-540c-11ea-9463-667d1074411e.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74991635-1365c980-540c-11ea-8ab7-ecf885a37ffd.png)

## Sidebar

- [x] the title and views for the video thumbnails should be at the right and not at the bottom

- Yours

![image](https://user-images.githubusercontent.com/52209067/74991724-6e97bc00-540c-11ea-9edb-86b4c919b88c.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74991761-88390380-540c-11ea-91a4-21cbbfab2ec3.png)

## General

* [x] I have found commented code in your CSS file please remove it I have put comments bellow where you can find them :arrow_double_down: 
* [x] I also have found inline styling in your HTML file, please remove it and add all style selectors in the CSS file you can only use ID's and classes in your HTML file :arrow_double_down: 

### That's it, team! :raised_hands: 

### Please :pray: do the changes :memo:  and submit back for a code review when you are done :rocket: 

Happy Coding! :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-02-21 00:24 UTC, euqueme commented on css/style.css
> +	height: 100%; */
remove all commented code

2020-02-21 00:24 UTC, euqueme commented on css/style.css
> +}
Remove this commented Id #blue-hr

2020-02-21 00:24 UTC, euqueme commented on css/style.css
> +}
remove this commented id #like-dislike

2020-02-21 00:24 UTC, euqueme commented on index.html
> +        <img alt="YouTube Logo" src="images/yt-logo.jpg" width="100" height="128" class="logo">
move the **width** and **height** selectors to a class in your CSS file

2020-02-21 00:24 UTC, euqueme commented on index.html
> +        <img alt="Photo-camera picture" src="images/photo-camera.jpg" height="30" width="40" id="photo-camera-img">
move the **width** and **height** selectors to a class in your CSS file lines #24 to #26

2020-02-21 00:24 UTC, euqueme commented on index.html
> +      <iframe width="650" height="360" src="https://www.youtube.com/embed/V74l_zS1x8E"
move the **width** and **height** selectors to a class in your CSS file

2020-02-21 18:08 UTC, majovanilla commented
Hey @Maclenn77  and @markonikovic  , 👋

## Good job on implementing the requested changes on this project! 👍

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- check your [HTML in the validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fgithub.com%2FMaclenn77%2FProject-Embeding-Videos%2Fblob%2Fgrid-styling%2Findex.html). You have several errors and warnings. :warning: 
![Screenshot from 2020-02-21 11-55-27](https://user-images.githubusercontent.com/51926937/75058814-53c35700-54a1-11ea-9b3e-89f506077f94.png)

- After implementing the previous required changes, your page looks a little different from the original one, especially with the positioning of some icons and elements. Please change them to look like the real youtube page :smile: 

In your page, the embedded video doesn't have the appropriate size and positioning. I should be aligned to the right, next to the suggested videos:

![Screenshot from 2020-02-21 12-07-28](https://user-images.githubusercontent.com/51926937/75059556-d862a500-54a2-11ea-81ea-f3012b0ca2cf.png)

Original:

![Screenshot from 2020-02-21 12-07-35](https://user-images.githubusercontent.com/51926937/75059563-dd275900-54a2-11ea-839a-6e78dcb0135b.png)

In your page the line that separates the video title is forcing the icons to move to the right side and below. Also, the suscribe button is in the opposite side.

![Screenshot from 2020-02-21 11-54-28](https://user-images.githubusercontent.com/51926937/75059024-b4529400-54a1-11ea-9f2c-f19b7c272586.png)

Original page:

![Screenshot from 2020-02-21 11-54-35](https://user-images.githubusercontent.com/51926937/75059224-1dd2a280-54a2-11ea-81b7-0ba51f2acdf0.png)

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- Change the size of your nav icons and the youtube logo to avoid losing proportion. This will make them look better.

![Screenshot from 2020-02-21 12-04-15](https://user-images.githubusercontent.com/51926937/75059307-4eb2d780-54a2-11ea-8b2b-af9776d93ea8.png)

- Add some description to the suggested videos to make your page look closely to the original one.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

2020-02-21 23:37 UTC, SofiBretz commented
### Changes required ♻️
### Hello team 🌟

Great work on this project, but we need to fix the issues below before moving on ⬇️

- [ ] Consider the positioning of the icons and elements, please make this look like the original page (Icons: 'likes', 'share', 'save'.. has to be in one single line as the original page)

![3](https://user-images.githubusercontent.com/42303392/75080069-a58fcf80-54e9-11ea-929e-6aa67d203f00.PNG)


![3 1](https://user-images.githubusercontent.com/42303392/75080074-aa548380-54e9-11ea-8687-c6fa0de43840.PNG)

- [ ] Consider that the embedded video doesn't have the appropriate size and positioning. I should be aligned to the right, next to the suggested videos.

![1](https://user-images.githubusercontent.com/42303392/75079556-dff86d00-54e7-11ea-83c0-3c06a28f9381.PNG)

![1 2](https://user-images.githubusercontent.com/42303392/75079560-e4bd2100-54e7-11ea-9fd6-6f39c76516cc.PNG)

- [ ] Consider that the subscribe button is on the opposite side, please put it on the right as the original page.

![2](https://user-images.githubusercontent.com/42303392/75079615-18984680-54e8-11ea-8dde-018ae5d8d818.PNG)

![2 2](https://user-images.githubusercontent.com/42303392/75079648-39f93280-54e8-11ea-8e20-c51c522aaee4.PNG)

[OPTIONAL]

- [ ] You are still missing the comment section. You can include only one or two comments to display it.

- [ ] Please add a demo link in your readme file.

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

2020-02-24 15:32 UTC, Maclenn77 commented
Hi, Sofi! 

We commented @Marijo by Slack that the page should look like this version of YouTube website: http://archive.ph/Bss88, not like the current one. So, she said that these changes weren't required:

>     * [ ]  Consider the positioning of the icons and elements, please make this look like the original page (Icons: 'likes', 'share', 'save'.. has to be in one single line as the original page)
> 
> 
> ![3](https://user-images.githubusercontent.com/42303392/75080069-a58fcf80-54e9-11ea-929e-6aa67d203f00.PNG)
> 
> ![3 1](https://user-images.githubusercontent.com/42303392/75080074-aa548380-54e9-11ea-8687-c6fa0de43840.PNG)
> 
>     * [ ]  Consider that the subscribe button is on the opposite side, please put it on the right as the original page.
> 
> 
> ![2](https://user-images.githubusercontent.com/42303392/75079615-18984680-54e8-11ea-8dde-018ae5d8d818.PNG)

We fixed the other problems. Greetings, and thx!

2020-02-24 17:33 UTC, pelzolga123 approved these changes
Approved.

2020-02-24 17:33 UTC, pelzolga123 commented
## Hi Team,
## Project looks amazing. Congratulation :+1: Approved.
I will ask you for one more thing, `node modules` folder should never be present in your repository, so please delete it. You can always use `.gitignore` file to prevent it from commiting said folder next time. 
Then go ahead and merge to master.

_Goodluck in your next project_ *Happy coding*

2020-02-24 17:36 UTC, merged